[package]
name = "yass-codegen"
version = "0.1.0"
authors = ["Eduardo Sánchez Muñoz <esm@eduardosm.net>"]
description = "Code generator for YASS schemas"
repository = "https://github.com/eduardosm/rust-yass"
license = "MIT/Apache-2.0"

[dependencies]
