[package]
name = "yass-parser"
version = "0.1.1"
authors = ["Eduardo Sánchez Muñoz <esm@eduardosm.net>"]
description = "YASS parser"
repository = "https://github.com/eduardosm/rust-yass"
license = "MIT/Apache-2.0"

[dependencies]
yass = { path = "../yass", version = "=0.1.1" }
